apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin-restapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-gin-restapi
  template:
    metadata:
      labels:
        app: go-gin-restapi
    spec:
      containers:
        - image: isshi/go-gin-restapi-example
          name: go-gin-restapi
          ports:
            - containerPort: 3000
